/**
 * PDF 导出工具
 * 使用 jsPDF 将产品卡片数据导出为 .pdf 文件（浏览器端生成）
 */
import { jsPDF } from 'jspdf'

interface ProductData {
  name: string
  tagline: string
  tags: string[]
  detail: string
  sources: Array<{ title: string; domain: string; url: string }>
}

export async function exportToPDF(
  products: ProductData[],
  title: string = '画布产品数据'
): Promise<Blob> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  const PAGE_W = 210
  const MARGIN = 20
  const CONTENT_W = PAGE_W - MARGIN * 2
  const LINE_H = 6
  const PAGE_H = 297

  let y = MARGIN

  // --- 封面 ---
  doc.setFillColor(245, 243, 255) // light purple bg
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(24)
  doc.setTextColor(31, 41, 55)
  doc.text(title, PAGE_W / 2, 80, { align: 'center' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(14)
  doc.setTextColor(107, 114, 128)
  doc.text(`${products.length} products`, PAGE_W / 2, 95, { align: 'center' })

  const dateStr = new Date().toLocaleDateString('zh-CN', { year: 'numeric', month: 'long', day: 'numeric' })
  doc.setFontSize(11)
  doc.setTextColor(156, 163, 175)
  doc.text(dateStr, PAGE_W / 2, 110, { align: 'center' })

  doc.text('Generated by Canvas Agent', PAGE_W / 2, 120, { align: 'center' })

  // --- 内容页 ---
  for (let i = 0; i < products.length; i++) {
    const p = products[i]

    doc.addPage()
    y = MARGIN

    // 白色背景
    doc.setFillColor(255, 255, 255)
    doc.rect(0, 0, PAGE_W, PAGE_H, 'F')

    // 页码
    doc.setFontSize(9)
    doc.setTextColor(156, 163, 175)
    doc.text(`${i + 1} / ${products.length}`, PAGE_W - MARGIN, PAGE_H - 10, { align: 'right' })

    // 产品名称
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(18)
    doc.setTextColor(31, 41, 55)
    doc.text(p.name, MARGIN, y)
    y += 10

    // tagline
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.setTextColor(107, 114, 128)
    doc.text(p.tagline, MARGIN, y)
    y += 8

    // 标签
    if (p.tags.length > 0) {
      doc.setFontSize(10)
      doc.setTextColor(124, 58, 237) // purple
      doc.text(p.tags.join('  |  '), MARGIN, y)
      y += 8
    }

    // 分隔线
    doc.setDrawColor(229, 231, 235)
    doc.setLineWidth(0.5)
    doc.line(MARGIN, y, PAGE_W - MARGIN, y)
    y += 8

    // 详细分析
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(55, 65, 81)

    const detailLines = doc.splitTextToSize(p.detail, CONTENT_W)
    for (const line of detailLines) {
      if (y > PAGE_H - 30) {
        doc.addPage()
        y = MARGIN
        // 续页页码
        doc.setFontSize(9)
        doc.setTextColor(156, 163, 175)
        doc.text(`${i + 1} / ${products.length} (cont.)`, PAGE_W - MARGIN, PAGE_H - 10, { align: 'right' })
        doc.setFontSize(10)
        doc.setTextColor(55, 65, 81)
      }
      doc.text(line, MARGIN, y)
      y += LINE_H
    }

    // 来源
    if (p.sources.length > 0) {
      y += 4
      if (y > PAGE_H - 30) {
        doc.addPage()
        y = MARGIN
      }

      doc.setDrawColor(229, 231, 235)
      doc.line(MARGIN, y, PAGE_W - MARGIN, y)
      y += 6

      doc.setFont('helvetica', 'bold')
      doc.setFontSize(9)
      doc.setTextColor(107, 114, 128)
      doc.text('Sources:', MARGIN, y)
      y += 5

      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      for (const src of p.sources) {
        if (y > PAGE_H - 15) {
          doc.addPage()
          y = MARGIN
        }
        doc.setTextColor(107, 114, 128)
        const srcText = `${src.title} — ${src.url}`
        doc.text(srcText, MARGIN + 2, y)
        y += 4
      }
    }
  }

  const blob = doc.output('blob')
  return blob
}
